name: Comment on Pull Request

on:
  pull_request:
    types: [opened]

permissions:
  issues: write
  pull-requests: write

jobs:
  comment:
    runs-on: ubuntu-latest

    steps:
      - name: Comment on PR
        uses: actions/github-script@v6
        with:
          script: |
            const issueNumber = context.payload.pull_request.number;
            const commentBase = 'Obrigado por abrir essa Pull Request! Vamos revisar em breve.\n\nArquivos alterados:\n';
            
            // Obter a lista de arquivos alterados
            const { data: files } = await github.rest.pulls.listFiles({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: issueNumber,
            });
            
            let comment = commentBase;
            
            if (!files || files.length === 0) {
              comment += 'Nenhum arquivo alterado.\n';
            } else {
              // Obter o patch da Pull Request
              const { data: pullRequestData } = await github.rest.pulls.get({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: issueNumber,
              });
              
              // Verifique se pullRequestData.files está definido
              if (pullRequestData.files) {
                for (const file of pullRequestData.files) {
                  const filePatch = file.patch || 'Sem alterações';
                  
                  comment += `**${file.filename}**\n`;
                  comment += `\`\`\`\n${filePatch}\n\`\`\`\n\n`;
                }
              } else {
                comment += 'Não foi possível obter as alterações dos arquivos.\n';
              }
            }
            
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issueNumber,
              body: comment,
            });
