name: Comment on Pull Request

on:
  pull_request:
    types: [opened]

permissions:
  issues: write
  pull_requests: write

jobs:
  comment:
    runs-on: ubuntu-latest

    steps:
      - name: Comment on PR
        uses: actions/github-script@v6
        with:
          script: |
            const issueNumber = context.payload.pull_request.number;
            const comment = 'Obrigado por abrir essa Pull Request! Vamos revisar em breve.';
            
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issueNumber,
              body: comment,
            });
